### ISSUE TITLE
Dockerise the application by adding a docker file

### ISSUE THREAD

**Issue by itachi9604** [itachi9604/query-app-ai#1]
Creating a Dockerfile to containerise the application.

while running docker image, it should accept one variable (-e ) that will serve as environment variable for API_KEY . 

example: 
docker run -e API_KEY = <API_KEY> <image_name>

**Comment by Badrri-Narayanan** [comment]
Hi, can you please assign this issue to me?

**Comment by itachi9604** [comment]
Hi @Badrri-Narayanan , can you please create a pull request by forking?
